using DevDefined.OAuth.Framework;
using DevDefined.OAuth.Storage.Basic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AtlassianConnector.Service
{


    /// <summary>
    /// Base interface for any http library implementation. 
    /// Need to provide OAuth1.0 support.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public interface IBaseService<T>
    {


        /// <summary>
        /// HTTP GET operation.
        /// </summary>
        /// <typeparam name="K">Result of Get operation. Might be some type of Response object or deserialized model class object.</typeparam>
        /// <param name="resource">Resource identifier. (e. g. spaces, content, user?id=1)</param>
        /// <param name="resourceContext">Url context specifying path to resource. (e. g. /api/agile/latest)</param>
        /// <returns></returns>
        K Get<K>(string resource, string resourceContext) where K : new();

        /// <summary>
        /// HTTP POST operation.
        /// </summary>
        /// <param name="resource">Resource identifier. (e. g. spaces, content, user?id=1)</param>
        /// <param name="resourceContext">Url context specifying path to resource. (e. g. /api/agile/latest)</param>
        /// <param name="content">Content to send.</param>
        /// <returns></returns>
        void Post(string resource, string resourceContext, byte[] content);

        /// <summary>
        /// HTTP PUT operation.
        /// </summary>
        /// <param name="resource">Resource identifier. (e. g. spaces, content, user?id=1)</param>
        /// <param name="resourceContext">Url context specifying path to resource. (e. g. /api/agile/latest)</param>
        /// <param name="content">Content to send.</param>
        /// <returns></returns>
        void Put(string resource, string resourceContext, byte[] content);

        /// <summary>
        /// Step 1 of OAuth1.0 dance. Obtains request token needed for further steps.
        /// </summary>
        /// <returns>Response object representing or containing OAuth request token.</returns>
        T GetRequestToken();


        /// <summary>
        /// Step 2 of OAUth1.0 dance. Obtains url for token authorization. Real user needs to be redirected to this url for signing-in and confirmation of granting the rights.
        /// </summary>
        /// <param name="requestToken">Request token object obtained from step 1 method of the OAuth1.0 dance.</param>
        /// <returns>URL address redirecting to token authorization.</returns>
        string GetUserAuthorizationUrlForToken(T requestToken);


        /// <summary>
        /// Step 3 of OAuth1.0 dance. Obtains access token in exchange for request token from previous steps and verification code provided by real user.
        /// </summary>
        /// <param name="requestToken">Request token object obtained from step 1 method of the OAuth1.0 dance.</param>
        /// <param name="verificationCode">Code generated by Jira app and provided to real user.</param>
        /// <returns>Response object representing or containing OAuth access token.</returns>
        T ExchangeRequestTokenForAccessToken(T requestToken, string verificationCode);
    }
}
