using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AtlassianConnector.Base
{

    /// <summary>
    /// Base interface for any http library supporting OAuth 1.0 process
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public interface IBaseOAuthService<T> : IBaseService
    {

        /// <summary>
        /// Step 1 of OAuth1.0 dance. Obtains request token needed for further steps.
        /// </summary>
        /// <returns>Response object representing or containing OAuth request token.</returns>
        T GetRequestToken();


        /// <summary>
        /// Step 2 of OAUth1.0 dance. Obtains url for token authorization. Real user needs to be redirected to this url for signing-in and confirmation of granting the rights.
        /// </summary>
        /// <param name="requestToken">Request token object obtained from step 1 method of the OAuth1.0 dance.</param>
        /// <returns>URL address redirecting to token authorization.</returns>
        string GetUserAuthorizationUrlForToken(T requestToken);


        /// <summary>
        /// Step 3 of OAuth1.0 dance. Obtains access token in exchange for request token from previous steps and verification code provided by real user.
        /// </summary>
        /// <param name="requestToken">Request token object obtained from step 1 method of the OAuth1.0 dance.</param>
        /// <param name="verificationCode">Code generated by Jira app and provided to real user.</param>
        /// <returns>Response object representing or containing OAuth access token.</returns>
        T ExchangeRequestTokenForAccessToken(T requestToken, string verificationCode);

    }
}
